//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YallaBaity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YallaBaity.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string lbAbout {
            get {
                return ResourceManager.GetString("lbAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string lbAccount {
            get {
                return ResourceManager.GetString("lbAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lbActive {
            get {
                return ResourceManager.GetString("lbActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string lbAdd {
            get {
                return ResourceManager.GetString("lbAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a food.
        /// </summary>
        public static string lbAddAFood {
            get {
                return ResourceManager.GetString("lbAddAFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Another Size.
        /// </summary>
        public static string lbAddAnotherSize {
            get {
                return ResourceManager.GetString("lbAddAnotherSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a profile picture.
        /// </summary>
        public static string lbAddAProfilePicture {
            get {
                return ResourceManager.GetString("lbAddAProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Images.
        /// </summary>
        public static string lbAddImages {
            get {
                return ResourceManager.GetString("lbAddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        public static string lbAddLocation {
            get {
                return ResourceManager.GetString("lbAddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lbAddress {
            get {
                return ResourceManager.GetString("lbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string lbAddresses {
            get {
                return ResourceManager.GetString("lbAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Name.
        /// </summary>
        public static string lbAddressName {
            get {
                return ResourceManager.GetString("lbAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string lbAddToCart {
            get {
                return ResourceManager.GetString("lbAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string lbAll {
            get {
                return ResourceManager.GetString("lbAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already added to cart.
        /// </summary>
        public static string lbAlreadyAddedToCart {
            get {
                return ResourceManager.GetString("lbAlreadyAddedToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment No.
        /// </summary>
        public static string lbApartmentNo {
            get {
                return ResourceManager.GetString("lbApartmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description.
        /// </summary>
        public static string lbArabicDescription {
            get {
                return ResourceManager.GetString("lbArabicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string lbArabicName {
            get {
                return ResourceManager.GetString("lbArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority.
        /// </summary>
        public static string lbAuthority {
            get {
                return ResourceManager.GetString("lbAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string lbBackgroundColor {
            get {
                return ResourceManager.GetString("lbBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Quality.
        /// </summary>
        public static string lbBestQuality {
            get {
                return ResourceManager.GetString("lbBestQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be The Fastest In Delivering Your Food.
        /// </summary>
        public static string lbBeTheFastestInDeliveringYourFood {
            get {
                return ResourceManager.GetString("lbBeTheFastestInDeliveringYourFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse foods.
        /// </summary>
        public static string lbBrowseFoods {
            get {
                return ResourceManager.GetString("lbBrowseFoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building No.
        /// </summary>
        public static string lbBuildingNo {
            get {
                return ResourceManager.GetString("lbBuildingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string lbCart {
            get {
                return ResourceManager.GetString("lbCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string lbCash {
            get {
                return ResourceManager.GetString("lbCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string lbCategories {
            get {
                return ResourceManager.GetString("lbCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lbCategoryName {
            get {
                return ResourceManager.GetString("lbCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorys.
        /// </summary>
        public static string lbCategorys {
            get {
                return ResourceManager.GetString("lbCategorys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my password.
        /// </summary>
        public static string lbChangeMyPassword {
            get {
                return ResourceManager.GetString("lbChangeMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my phone.
        /// </summary>
        public static string lbChangeMyPhone {
            get {
                return ResourceManager.GetString("lbChangeMyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Choose --.
        /// </summary>
        public static string lbChosse {
            get {
                return ResourceManager.GetString("lbChosse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add the back of the card.
        /// </summary>
        public static string lbClickToAddTheBackOfTheCard {
            get {
                return ResourceManager.GetString("lbClickToAddTheBackOfTheCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add the front of the card.
        /// </summary>
        public static string lbClickToAddTheFrontOfTheCard {
            get {
                return ResourceManager.GetString("lbClickToAddTheFrontOfTheCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string lbClose {
            get {
                return ResourceManager.GetString("lbClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lbCode {
            get {
                return ResourceManager.GetString("lbCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the order.
        /// </summary>
        public static string lbCompleteTheOrder {
            get {
                return ResourceManager.GetString("lbCompleteTheOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the request.
        /// </summary>
        public static string lbCompleteTheRequest {
            get {
                return ResourceManager.GetString("lbCompleteTheRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string lbConfirm {
            get {
                return ResourceManager.GetString("lbConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Location.
        /// </summary>
        public static string lbConfirmLocation {
            get {
                return ResourceManager.GetString("lbConfirmLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string lbConfirmPassword {
            get {
                return ResourceManager.GetString("lbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string lbContact {
            get {
                return ResourceManager.GetString("lbContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string lbCreateAnAccount {
            get {
                return ResourceManager.GetString("lbCreateAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string lbCreateNew {
            get {
                return ResourceManager.GetString("lbCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard Users.
        /// </summary>
        public static string lbDashBoardUsers {
            get {
                return ResourceManager.GetString("lbDashBoardUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit/Credit Card.
        /// </summary>
        public static string lbDebitCreditCard {
            get {
                return ResourceManager.GetString("lbDebitCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lbDelete {
            get {
                return ResourceManager.GetString("lbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver to.
        /// </summary>
        public static string lbDeliverTo {
            get {
                return ResourceManager.GetString("lbDeliverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string lbDelivery {
            get {
                return ResourceManager.GetString("lbDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string lbDeliveryDate {
            get {
                return ResourceManager.GetString("lbDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery that is always on time even faster.
        /// </summary>
        public static string lbDeliveryThatIsAlwaysOnTimeEvenFaster {
            get {
                return ResourceManager.GetString("lbDeliveryThatIsAlwaysOnTimeEvenFaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Time.
        /// </summary>
        public static string lbDeliveryTime {
            get {
                return ResourceManager.GetString("lbDeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lbDescription {
            get {
                return ResourceManager.GetString("lbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover Baity food wherever and whenever and get your food delivered quickly..
        /// </summary>
        public static string lbDiscoverBaityFood {
            get {
                return ResourceManager.GetString("lbDiscoverBaityFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string lbDontHaveAnAccount {
            get {
                return ResourceManager.GetString("lbDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download App.
        /// </summary>
        public static string lbDownloadApp {
            get {
                return ResourceManager.GetString("lbDownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an account?.
        /// </summary>
        public static string lbDoYouHaveAnAccount {
            get {
                return ResourceManager.GetString("lbDoYouHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy To Order.
        /// </summary>
        public static string lbEasyToOrder {
            get {
                return ResourceManager.GetString("lbEasyToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid.
        /// </summary>
        public static string lbEmailFormatIsInvalidMsg {
            get {
                return ResourceManager.GetString("lbEmailFormatIsInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        public static string lbEnglishDescription {
            get {
                return ResourceManager.GetString("lbEnglishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English  Name.
        /// </summary>
        public static string lbEnglishName {
            get {
                return ResourceManager.GetString("lbEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 4-digit code.
        /// </summary>
        public static string lbEnterThe4DigitCode {
            get {
                return ResourceManager.GetString("lbEnterThe4DigitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone correctly.
        /// </summary>
        public static string lbEnterThePhoneCorrectly {
            get {
                return ResourceManager.GetString("lbEnterThePhoneCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        public static string lbError {
            get {
                return ResourceManager.GetString("lbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest Delivery.
        /// </summary>
        public static string lbFastestDelivery {
            get {
                return ResourceManager.GetString("lbFastestDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string lbFemale {
            get {
                return ResourceManager.GetString("lbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor No.
        /// </summary>
        public static string lbFloorNo {
            get {
                return ResourceManager.GetString("lbFloorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food details.
        /// </summary>
        public static string lbFoodDetails {
            get {
                return ResourceManager.GetString("lbFoodDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Pending.
        /// </summary>
        public static string lbFoodPending {
            get {
                return ResourceManager.GetString("lbFoodPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foods.
        /// </summary>
        public static string lbFoods {
            get {
                return ResourceManager.GetString("lbFoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lbGender {
            get {
                return ResourceManager.GetString("lbGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started With Go Baity Today!.
        /// </summary>
        public static string lbGetStartedWithGoBaityToday {
            get {
                return ResourceManager.GetString("lbGetStartedWithGoBaityToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get The App.
        /// </summary>
        public static string lbGetTheApp {
            get {
                return ResourceManager.GetString("lbGetTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorate.
        /// </summary>
        public static string lbGovernorate {
            get {
                return ResourceManager.GetString("lbGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string lbGroup {
            get {
                return ResourceManager.GetString("lbGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Permission.
        /// </summary>
        public static string lbGroupPermission {
            get {
                return ResourceManager.GetString("lbGroupPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string lbGroups {
            get {
                return ResourceManager.GetString("lbGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lbHome {
            get {
                return ResourceManager.GetString("lbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lbImage {
            get {
                return ResourceManager.GetString("lbImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect phone format.
        /// </summary>
        public static string lbIncorrectPhoneFormat {
            get {
                return ResourceManager.GetString("lbIncorrectPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username.
        /// </summary>
        public static string lbIncorrectUsername {
            get {
                return ResourceManager.GetString("lbIncorrectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string lbItems {
            get {
                return ResourceManager.GetString("lbItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join as a provider.
        /// </summary>
        public static string lbJoinAsAProvider {
            get {
                return ResourceManager.GetString("lbJoinAsAProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string lbLatest {
            get {
                return ResourceManager.GetString("lbLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lbLocation {
            get {
                return ResourceManager.GetString("lbLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lbLogin {
            get {
                return ResourceManager.GetString("lbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string lbLogout {
            get {
                return ResourceManager.GetString("lbLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string lbMale {
            get {
                return ResourceManager.GetString("lbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string lbMinute {
            get {
                return ResourceManager.GetString("lbMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular.
        /// </summary>
        public static string lbMostPopular {
            get {
                return ResourceManager.GetString("lbMostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My foods.
        /// </summary>
        public static string lbMyFoods {
            get {
                return ResourceManager.GetString("lbMyFoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My orders.
        /// </summary>
        public static string lbMyOrders {
            get {
                return ResourceManager.GetString("lbMyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lbName {
            get {
                return ResourceManager.GetString("lbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National card Back.
        /// </summary>
        public static string lbNationalCardBack {
            get {
                return ResourceManager.GetString("lbNationalCardBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National card Face.
        /// </summary>
        public static string lbNationalCardFace {
            get {
                return ResourceManager.GetString("lbNationalCardFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        public static string lbNet {
            get {
                return ResourceManager.GetString("lbNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string lbNewPassword {
            get {
                return ResourceManager.GetString("lbNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not only fast for us quality is also number one.
        /// </summary>
        public static string lbNotOnlyFastForUsQualityIsAlsoNumberOne {
            get {
                return ResourceManager.GetString("lbNotOnlyFastForUsQualityIsAlsoNumberOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string lbNow {
            get {
                return ResourceManager.GetString("lbNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string lbOldPassword {
            get {
                return ResourceManager.GetString("lbOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Data.
        /// </summary>
        public static string lbOrderData {
            get {
                return ResourceManager.GetString("lbOrderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string lbOrderDate {
            get {
                return ResourceManager.GetString("lbOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string lbOrderNumber {
            get {
                return ResourceManager.GetString("lbOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string lbOrderStatus {
            get {
                return ResourceManager.GetString("lbOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other food for.
        /// </summary>
        public static string lbOtherFoodFor {
            get {
                return ResourceManager.GetString("lbOtherFoodFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment and delivery time.
        /// </summary>
        public static string lbPaymentAndDeliveryTime {
            get {
                return ResourceManager.GetString("lbPaymentAndDeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string lbPaymentMethod {
            get {
                return ResourceManager.GetString("lbPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Image.
        /// </summary>
        public static string lbPersonalImage {
            get {
                return ResourceManager.GetString("lbPersonalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lbPhone {
            get {
                return ResourceManager.GetString("lbPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the size.
        /// </summary>
        public static string lbPleaseChooseTheSize {
            get {
                return ResourceManager.GetString("lbPleaseChooseTheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the information.
        /// </summary>
        public static string lbPleaseCompleteTheInformation {
            get {
                return ResourceManager.GetString("lbPleaseCompleteTheInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the OTP code.
        /// </summary>
        public static string lbPleaseConfirmTheOTPCode {
            get {
                return ResourceManager.GetString("lbPleaseConfirmTheOTPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the confirmation number.
        /// </summary>
        public static string lbPleaseEnterTheConfirmationNumber {
            get {
                return ResourceManager.GetString("lbPleaseEnterTheConfirmationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login first.
        /// </summary>
        public static string lbPleaseLoginFirst {
            get {
                return ResourceManager.GetString("lbPleaseLoginFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in.
        /// </summary>
        public static string lbPleaseSignIn {
            get {
                return ResourceManager.GetString("lbPleaseSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation Time.
        /// </summary>
        public static string lbPreparationTime {
            get {
                return ResourceManager.GetString("lbPreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lbPrice {
            get {
                return ResourceManager.GetString("lbPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile personly.
        /// </summary>
        public static string lbProfilePersonly {
            get {
                return ResourceManager.GetString("lbProfilePersonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string lbProviders {
            get {
                return ResourceManager.GetString("lbProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Pending.
        /// </summary>
        public static string lbProvidersPending {
            get {
                return ResourceManager.GetString("lbProvidersPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string lbRating {
            get {
                return ResourceManager.GetString("lbRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string lbRegisterNow {
            get {
                return ResourceManager.GetString("lbRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is requird.
        /// </summary>
        public static string lbRequirdMsg {
            get {
                return ResourceManager.GetString("lbRequirdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string lbReviews {
            get {
                return ResourceManager.GetString("lbReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Order.
        /// </summary>
        public static string lbScheduleOrder {
            get {
                return ResourceManager.GetString("lbScheduleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lbSearch {
            get {
                return ResourceManager.GetString("lbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Payment Method.
        /// </summary>
        public static string lbSelectYourPaymentMethod {
            get {
                return ResourceManager.GetString("lbSelectYourPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send OTP Again.
        /// </summary>
        public static string lbSendOTPAgain {
            get {
                return ResourceManager.GetString("lbSendOTPAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ser..
        /// </summary>
        public static string lbSerial {
            get {
                return ResourceManager.GetString("lbSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        public static string lbSizes {
            get {
                return ResourceManager.GetString("lbSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string lbSortBy {
            get {
                return ResourceManager.GetString("lbSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Ordering.
        /// </summary>
        public static string lbStartOrdering {
            get {
                return ResourceManager.GetString("lbStartOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string lbStreet {
            get {
                return ResourceManager.GetString("lbStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit for review.
        /// </summary>
        public static string lbSubmitForReview {
            get {
                return ResourceManager.GetString("lbSubmitForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string lbTab {
            get {
                return ResourceManager.GetString("lbTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location has been added.
        /// </summary>
        public static string lbTheLocationHasBeenAdded {
            get {
                return ResourceManager.GetString("lbTheLocationHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was completed successfully.
        /// </summary>
        public static string lbTheOperationWasCompletedSuccessfully {
            get {
                return ResourceManager.GetString("lbTheOperationWasCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP number is incorrect.
        /// </summary>
        public static string lbTheOTPNumberIsIncorrect {
            get {
                return ResourceManager.GetString("lbTheOTPNumberIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        public static string lbThePasswordIsIncorrect {
            get {
                return ResourceManager.GetString("lbThePasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no foods in the basket.
        /// </summary>
        public static string lbThereAreNoFoodsInTheBasket {
            get {
                return ResourceManager.GetString("lbThereAreNoFoodsInTheBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two passwords do not match.
        /// </summary>
        public static string lbTheTwoPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("lbTheTwoPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is inactive.
        /// </summary>
        public static string lbThisAccountIsInactive {
            get {
                return ResourceManager.GetString("lbThisAccountIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already registered.
        /// </summary>
        public static string lbThisEmailIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("lbThisEmailIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already registered.
        /// </summary>
        public static string lbThisNameIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("lbThisNameIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone has already been registered.
        /// </summary>
        public static string lbThisPhoneHasAlreadyBeenRegistered {
            get {
                return ResourceManager.GetString("lbThisPhoneHasAlreadyBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone is not registered.
        /// </summary>
        public static string lbThisPhoneIsNotRegistered {
            get {
                return ResourceManager.GetString("lbThisPhoneIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record is linked to other records.
        /// </summary>
        public static string lbThisRecordIsLinkedToOtherRecords {
            get {
                return ResourceManager.GetString("lbThisRecordIsLinkedToOtherRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not a provider.
        /// </summary>
        public static string lbThisUserIsNotAProvider {
            get {
                return ResourceManager.GetString("lbThisUserIsNotAProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lbTotal {
            get {
                return ResourceManager.GetString("lbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lbUpdate {
            get {
                return ResourceManager.GetString("lbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string lbUpload {
            get {
                return ResourceManager.GetString("lbUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image.
        /// </summary>
        public static string lbUploadImage {
            get {
                return ResourceManager.GetString("lbUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lbUserName {
            get {
                return ResourceManager.GetString("lbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string lbUsers {
            get {
                return ResourceManager.GetString("lbUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string lbWelcome {
            get {
                return ResourceManager.GetString("lbWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why go Baity.
        /// </summary>
        public static string lbWhyGoBaity {
            get {
                return ResourceManager.GetString("lbWhyGoBaity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the maximum number of daily submissions.
        /// </summary>
        public static string lbYouHaveExceededTheMaximumNumberOfDailySubmissions {
            get {
                return ResourceManager.GetString("lbYouHaveExceededTheMaximumNumberOfDailySubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You only need a few steps in ordering food.
        /// </summary>
        public static string lbYouOnlyNeedAFewStepsInOrderingFood {
            get {
                return ResourceManager.GetString("lbYouOnlyNeedAFewStepsInOrderingFood", resourceCulture);
            }
        }
    }
}
